services:
  mongodb:
    image: mongo:7
    container_name: shopez-markets-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - shopez_mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: stocktrade

volumes:
  shopez_mongo_data:
